### ISSUE TITLE
If two users upload the same asset one user will not be able to use the asset

### ISSUE THREAD

**Issue by AddictArts** [adlnet/Sandbox#244]
Two users could load the same asset as each other without knowing. The first user will be able to add it to the scene. The second will get a permissions denied.
![permissions](https://cloud.githubusercontent.com/assets/911906/8759532/c6ef8c40-2caa-11e5-94db-04adcc6477ea.png)

**Comment by rchadwic** [comment]
Is this not expected behavior? The first user - whoever created the scene, has permission to add objects. The second user is allowed to upload content into their personal library, but cannot modify the scene.

**Comment by rchadwic** [comment]
I think I understand what is going on here. You've opened two tabs into the same environment, but using the same profile in Chrome. Thus - while the API correctly identifies you as the same person because of the cookie, we've for a long while made the socket  for a second connection with the same cookie anonymous. 

That's probably where the confusion is coming from... one of your tabs has an anonymous WebSocket, but still normal API access

**Comment by rchadwic** [comment]
Pivotal story link. https://www.pivotaltracker.com/story/show/99428270

**Comment by AddictArts** [comment]
I may have used the same browser, but I am fairly sure I logged complete out of one user then signed in as another. So, I was thinking it is expected, except why list the asset in My Models if you have zero permission? I was thinking it should just not show up.

**Comment by rchadwic** [comment]
So, the user is allowed to upload to their own library, but the user might not have permission on the world. We probably need a better GUI mode to show that you can't edit the world.
